// Auto-generated Supabase configuration
// Do not edit this file manually

export const projectId = 'ewjopuynehppzozgzsht';
export const publicAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3am9wdXluZWhwcHpvemd6c2h0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg0MDc4ODIsImV4cCI6MjA5Mzk4Mzg4Mn0.4rUmp0A1UAurA311E1fefCcxMIy23PAbuKlX2BCph24';
export const supabaseUrl = 'https://ewjopuynehppzozgzsht.supabase.co';
